'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class PRG_FIN_RECVBLE_ENTRY

    '''<summary>
    '''PRG_FIN_RECVBLE_ENTRY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PRG_FIN_RECVBLE_ENTRY As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''litMsgs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMsgs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesc1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRcptNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRcptNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtReceiptNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEntryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntryDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompanyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerialNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBatchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBatchDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbTransType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTransType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDept As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblRcptDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRcptDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEffectiveDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProgType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTellerNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTellerNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTellerDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTellerDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtChequeNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChequeNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtChequeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChequeDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbCurrencyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCurrencyType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''csValidateCurrencyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents csValidateCurrencyType As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cmbBranchCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBranchCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTotalAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Polyeffdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Polyeffdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPolicyEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolicyEffDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPayeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayeeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPayeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPayeeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemarks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTransDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTransDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''butSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butNew As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMainAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainAC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubAC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLedgerType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLedgerType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTranType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTranType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDRCR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDRCR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRef1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRef1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRef2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRef2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRef3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRef3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTranAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTranAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMainAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMainAcct As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSubAcct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubAcct As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLedgerType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLedgerType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbTransDetailType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTransDetailType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbDRCR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDRCR As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CustomValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomValidator1 As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''txtReceiptRefNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptRefNo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReceiptRefNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptRefNo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReceiptRefNo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiptRefNo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTransAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vdamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vdamt As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtSubSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubSerialNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRefDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRefDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRefAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRefAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''butSaveDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butSaveDetail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butNewDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butNewDetail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butDeleteDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butDeleteDetail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''butPrintDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butPrintDetail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtMainAcctDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMainAcctDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSubAcctDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubAcctDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRefDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefDesc1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRefDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefDesc2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRefDesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefDesc3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesc2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ods1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods1 As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''lblPrintLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRecptNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecptNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''butPrintReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butPrintReceipt As Global.System.Web.UI.WebControls.Button
End Class
